# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-alpine

# Set working directory
WORKDIR /app

# Install dependencies
RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev \
    && pip install --no-cache-dir fast-agent-mcp>=0.2.23 requests>=2.32.3 python-dotenv \
    && apk del .build-deps

# Copy application code
COPY main.py .

# Copy project metadata if needed
COPY pyproject.toml .

# Expose no ports (stdio transport)

# Default command
CMD ["python", "main.py"]
